/* ============
 * Orson Charts
 * ============
 * 
 * (C)opyright 2013, 2014, by Object Refinery Limited.
 * 
 * http://www.object-refinery.com/orsoncharts/index.html
 * 
 * Redistribution of this source file is prohibited.
 * 
 */

package com.orsoncharts.marker;

import java.util.EventObject;
import com.orsoncharts.util.ArgChecks;

/**
 * An event associated with a change to a {@link Marker}.  These change 
 * events will be generated by an marker and broadcast to the axis that owns the
 * marker (in the standard setup, the axis will then trigger its own change e
 * vent to notify the plot that a subcomponent of the axis has changed). 
 * 
 * @since 1.2
 */
public class MarkerChangeEvent extends EventObject {
  
    /** The marker associated with this event. */
    private Marker marker;
    
    /**
     * Creates a new event.
     * 
     * @param marker  the marker (<code>null</code> not permitted).
     */
    public MarkerChangeEvent(Marker marker) {
        this(marker, marker);
    }
    
    /**
     * Creates a new event.
     * 
     * @param source  the event source.
     * @param axis  the axis (<code>null</code> not permitted).
     */
    public MarkerChangeEvent(Object source, Marker marker) {
        super(source);
        ArgChecks.nullNotPermitted(marker, "marker");
        this.marker = marker;
    }
  
    /**
     * Returns the marker associated with this event.
     * 
     * @return The marker (never <code>null</code>). 
     */
    public Marker getMarker() {
        return this.marker;
    }

}
